version: "3.9"
services:
  knary:
    container_name: knary
    hostname: knary
    restart: always
    env_file:
      - .env # as below, you can also use the `environment` config to specify variables. This will override matching keys in `env_file`
    environment:
      - BIND_ADDR=0.0.0.0
    build: .
    ports:
      - "80:80"
      - "443:443"
      - "53:53/udp"
    volumes: # to save your LE config logs when the container stops
      - ./certs:/certs/
